[build]
  command = "vite build"
  functions = "netlify/functions"
  publish = "dist"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept"

[functions]
  node_bundler = "esbuild"

[dev]
  functions = "netlify/functions"
  publish = "dist"
  port = 8888

# Redirect all API calls to the serverless functions
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
